name: Check Substitutions

on:
  schedule:
    # Runs at 5 PM UTC = 7 PM CEST (German summer time)
    # Runs every day of the week
    - cron: '0 17 * * *'
    
    # Runs at 6 PM UTC = 7 PM CET (German winter time)
    # Runs every day of the week
    - cron: '0 18 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
          PDF_URL: ${{ secrets.PDF_URL }}
          GITHUB_ACTIONS: "true"
        run: python main.py
